# Site settings
title: Welcome to Nowhere
github_username:  pankdm

# Build settings
# markdown: kramdown
markdown: redcarpet
highlighter: pygments

kramdown:
  input: GFM
  hard_wrap: false

redcarpet:
  # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  extensions: ["tables"]

#Other
permalink: /:categories/:title.html
